# Generated by Django 4.1.7 on 2023-04-06 08:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('logo_text', models.CharField(blank=True, max_length=50, verbose_name='Logotype long')),
                ('logo_abreviation', models.CharField(blank=True, max_length=5, verbose_name='logo abbreviation')),
                ('logo_image', models.FileField(blank=True, upload_to='images/')),
                ('text_intro', models.TextField(blank=True)),
                ('text_intro_title', models.TextField(blank=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=50, verbose_name='Youtube video ID')),
                ('text_prologue_title', models.TextField(blank=True)),
                ('text_prologue', models.TextField(blank=True)),
                ('partners_logo', wagtail.fields.StreamField([('partners_logo_cards', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('width', wagtail.blocks.IntegerBlock(help_text='Width in % in block for all logos added', required=True)), ('partners_logo_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('logo_title', wagtail.blocks.CharBlock(max_length=200, required=False)), ('logo_url', wagtail.blocks.URLBlock(default='', help_text='logo owner site link', required=False))])))]))], blank=True, null=True, use_json_field=True)),
                ('projects_block', wagtail.fields.StreamField([('projects_block', wagtail.blocks.StructBlock([('title_projects', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('text_card', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('text', wagtail.blocks.CharBlock(max_length=300, required=False)), ('description', wagtail.blocks.CharBlock(max_length=300, required=False)), ('learn_more_url', wagtail.blocks.URLBlock(help_text='Link URL.', required=False))])))]))], blank=True, null=True, use_json_field=True)),
                ('why_block', wagtail.fields.StreamField([('text_why', wagtail.blocks.StructBlock([('title_why', wagtail.blocks.TextBlock(help_text='Add your why title', required=True)), ('text_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=300, required=False))])))]))], blank=True, null=True, use_json_field=True)),
                ('how_block', wagtail.fields.StreamField([('text_how', wagtail.blocks.StructBlock([('title_how', wagtail.blocks.TextBlock(help_text='Add your why title', required=True)), ('text_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=300, required=False))])))]))], blank=True, null=True, use_json_field=True)),
                ('who_block', wagtail.fields.StreamField([('text_who', wagtail.blocks.StructBlock([('title_who', wagtail.blocks.TextBlock(help_text='Add your title', required=True)), ('text_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=300, required=False))])))]))], blank=True, null=True, use_json_field=True)),
                ('guiding', wagtail.fields.StreamField([('text_guiding', wagtail.blocks.StructBlock([('title1', wagtail.blocks.TextBlock(help_text='Add your title', required=True)), ('text_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('number', wagtail.blocks.IntegerBlock(required=False)), ('title', wagtail.blocks.CharBlock(max_length=60, required=False)), ('description', wagtail.blocks.CharBlock(max_length=200, required=False))])))]))], blank=True, null=True, use_json_field=True)),
                ('text_list_next_title', models.TextField(blank=True)),
                ('text_list_next', models.TextField(blank=True)),
                ('media_about', wagtail.fields.StreamField([('cards_media', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=60, required=True)), ('button_url', wagtail.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False))])))]))], blank=True, null=True, use_json_field=True)),
                ('footer_logo', wagtail.fields.StreamField([('footer_logo_cards', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('width', wagtail.blocks.IntegerBlock(help_text='Width in vw for all logos added', required=True)), ('footer_logo_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('logo_title', wagtail.blocks.CharBlock(max_length=200, required=False)), ('logo_url', wagtail.blocks.URLBlock(default='', help_text='logo owner site link', required=False))])))]))], blank=True, null=True, use_json_field=True)),
                ('text_partners', models.TextField(blank=True)),
                ('text_copyright', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
