# Generated by Django 4.1.7 on 2023-02-15 20:18

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='footer_logo',
            field=wagtail.fields.StreamField([('footer_logo_cards', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('width', wagtail.blocks.IntegerBlock(help_text='Width in vw for all logos added', required=True)), ('footer_logo_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('logo_title', wagtail.blocks.CharBlock(max_length=200, required=False)), ('logo_url', wagtail.blocks.URLBlock(default='', help_text='logo owner site link', required=False))])))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='guiding',
            field=wagtail.fields.StreamField([('text_guiding', wagtail.blocks.StructBlock([('title1', wagtail.blocks.TextBlock(help_text='Add your title', required=True)), ('text_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('number', wagtail.blocks.IntegerBlock(required=False)), ('title', wagtail.blocks.CharBlock(max_length=60, required=False)), ('description', wagtail.blocks.CharBlock(max_length=200, required=False))])))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_abreviation',
            field=models.CharField(blank=True, max_length=5, verbose_name='logo abbreviation'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Logotype long'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='media_about',
            field=wagtail.fields.StreamField([('cards_media', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('title', wagtail.blocks.CharBlock(max_length=60, required=True)), ('button_url', wagtail.blocks.URLBlock(help_text='If the button page above is selected, that will be used first.', required=False))])))]))], blank=True, null=True, use_json_field=None),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_copyright',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_partners',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Youtube video ID'),
        ),
    ]
