# Generated by Django 4.1.7 on 2023-04-06 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='logo_image',
            field=models.FileField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png', 'jpg'])]),
        ),
    ]
