# Generated by Django 4.1.7 on 2023-02-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_footer_logo_homepage_guiding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_list_next',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='text_list_next_title',
            field=models.TextField(blank=True),
        ),
    ]
