# Generated by Django 4.1.9 on 2023-09-18 16:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_homepage_projects_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='guiding',
            field=wagtail.fields.StreamField([('text_guiding', wagtail.blocks.StructBlock([('title1', wagtail.blocks.TextBlock(help_text='Add your title', required=True)), ('text_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('number', wagtail.blocks.IntegerBlock(required=False)), ('title', wagtail.blocks.CharBlock(max_length=60, required=False)), ('description', wagtail.blocks.CharBlock(max_length=300, required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='how_block',
            field=wagtail.fields.StreamField([('text_how', wagtail.blocks.StructBlock([('title_how', wagtail.blocks.TextBlock(help_text='Add your why title', required=True)), ('text_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=400, required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='projects_block',
            field=wagtail.fields.StreamField([('projects_block', wagtail.blocks.StructBlock([('title_projects', wagtail.blocks.CharBlock(help_text='Add your title', required=True)), ('text_card', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('text', wagtail.blocks.CharBlock(max_length=400, required=False)), ('description', wagtail.blocks.CharBlock(max_length=400, required=False)), ('btn_name', wagtail.blocks.CharBlock(max_length=400, required=False)), ('learn_more_url', wagtail.blocks.URLBlock(help_text='Link URL.', required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='who_block',
            field=wagtail.fields.StreamField([('text_who', wagtail.blocks.StructBlock([('title_who', wagtail.blocks.TextBlock(help_text='Add your title', required=True)), ('text_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=500, required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='why_block',
            field=wagtail.fields.StreamField([('text_why', wagtail.blocks.StructBlock([('title_why', wagtail.blocks.TextBlock(help_text='Add your why title', required=True)), ('text_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=400, required=False))])))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
