# Generated by Django 4.1.7 on 2023-02-27 20:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_why_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='how_block',
            field=wagtail.fields.StreamField([('text_how', wagtail.blocks.StructBlock([('title_how', wagtail.blocks.TextBlock(help_text='Add your why title', required=True)), ('text_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=300, required=False))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
