# Generated by Django 4.1.7 on 2023-04-05 14:38

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_homepage_partners_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='projects_block',
            field=wagtail.fields.StreamField([('projects_block', wagtail.blocks.StructBlock([('title_who', wagtail.blocks.TextBlock(help_text='Add your title', required=True)), ('text_cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(max_length=300, required=False))])))]))], blank=True, null=True, use_json_field=None),
        ),
    ]
