# Generated by Django 4.1.7 on 2023-04-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_projects_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='logo_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
