# Generated by Django 4.1.7 on 2023-04-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_homepage_logo_img_homepage_text_intro_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='logo_image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
