# Generated by Django 4.1.7 on 2023-04-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_homepage_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='logo_img',
        ),
    ]
