version: "3.7"

services:
  ucc2web:
    build: .
    image: docker-ucc-app
    command: bash runserver.sh
    volumes:
      - .:/usr/src/app
    expose:
      - 8081:8082
    env_file:
      - env/app.env
      - env/database.env

