version: "3.7"

services:
  ucc2web:
    build: .
    image: docker-ucc-app
    command: sh runserver.sh
    volumes:
      - .:/usr/src/app
    ports:
      - 8081:8081
    env_file:
      - env/app.env
      - env/database.env

